(()=>{var tn=(n,t)=>()=>(t||n((t={exports:{}}).exports,t),t.exports);var ln=tn((an,v)=>{var sn=typeof globalThis!="undefined"&&globalThis.vendetta?globalThis.vendetta:typeof vendetta!="undefined"?vendetta:{},{plugin:C,patcher:cn,metro:$,ui:F,utils:on}=sn,f=C&&C.storage?C.storage:{},{after:H,before:q}=cn||{},{findByProps:A,findByStoreName:y}=$||{},{FluxDispatcher:E,React:Q}=$&&$.common||{},{findInReactTree:V}=on||{},{showToast:X}=F&&F.toasts||{},I=A?A("sendMessage","receiveMessage","editMessage"):void 0,L=y?y("MessageStore"):void 0,M=A?A("openLazy","hideActionSheet"):void 0,T=A?A("ActionSheetRow","ActionSheetSection","ActionSheetTitleHeader"):void 0;f.logs||(f.logs={});f.uiMessageIds||(f.uiMessageIds={});var _=[];function Y(n){return f.logs[n]||(f.logs[n]=[]),f.logs[n]}function Z(n){return f.uiMessageIds[n]||(f.uiMessageIds[n]=[]),f.uiMessageIds[n]}function p(n,t,e){var s,c;try{return(c=(s=L==null?void 0:L.getMessage)==null?void 0:s.call(L,n,t))!=null?c:e}catch(i){return e}}function rn(n){var e,s;if(!n)return"";let t=[];if(n.title&&t.push(`\u2022 ${n.title}`),n.description&&t.push(n.description),Array.isArray(n.fields)&&n.fields.length)for(let c of n.fields){if(!c)continue;let i=(e=c.name)!=null?e:"",o=(s=c.value)!=null?s:"";t.push(`${i}: ${o}`)}return n.url&&t.push(n.url),t.join(`
`)}function B(n){if(!Array.isArray(n)||n.length===0)return null;let t=n.map(rn).filter(Boolean);return t.length?t.join(`
---
`):null}function nn(n,t,e){if(!I||!I.receiveMessage)return;let s=`nodelete_${Date.now()}_${Math.floor(Math.random()*1e6)}`,c={id:s,type:0,flags:0,channel_id:n,content:t,author:{id:"0",username:"NoDelete",discriminator:"0000",avatar:null,bot:!0}};e&&(c.content+=`

Embeds:
${e}`);try{I.receiveMessage(n,c)}catch(i){}try{Z(n).push(s)}catch(i){}}function en(n){var g,l,h,r;let t=(g=n==null?void 0:n.channelId)!=null?g:n==null?void 0:n.channel_id,e=n==null?void 0:n.id;if(!t||!e||String(e).startsWith("nodelete_"))return;let s=(l=n==null?void 0:n.message)!=null?l:p(t,e,null);if(!s)return;let c=(h=s.author)!=null?h:{id:"unknown",username:"Unknown"},i=s.content||"",o=s.embeds||[],d=B(o);Y(t).push({type:"delete",messageId:e,channelId:t,author:c,timestamp:Date.now(),contentBefore:i,embedsBefore:o});let a=(r=c==null?void 0:c.username)!=null?r:"Unknown",u=i!=null&&i.length?i:"[no content]";nn(t,`deleted message by ${a}:
${u}`,d)}function un(n){var s;let t=(s=n==null?void 0:n.channelId)!=null?s:n==null?void 0:n.channel_id,e=n==null?void 0:n.ids;if(!(!t||!Array.isArray(e)))for(let c of e)String(c).startsWith("nodelete_")||en({channelId:t,id:c})}function fn(){if(!q||!E)return;let n=q("dispatch",E,([t])=>{var U,k,G,N,P,x,R,j,z,J,K,O,W;if(!t||t.type!=="MESSAGE_UPDATE")return;let e=t,s=(N=(k=e==null?void 0:e.channelId)!=null?k:(U=e==null?void 0:e.message)==null?void 0:U.channel_id)!=null?N:(G=e==null?void 0:e.message)==null?void 0:G.channelId,c=(x=(P=e==null?void 0:e.message)==null?void 0:P.id)!=null?x:e==null?void 0:e.id;if(!s||!c)return;let i=p(s,c,null),o=(R=e==null?void 0:e.message)!=null?R:null;if(!o)return;let d=(j=i==null?void 0:i.content)!=null?j:"",a=(z=o==null?void 0:o.content)!=null?z:"",u=(J=i==null?void 0:i.embeds)!=null?J:[],g=(K=o==null?void 0:o.embeds)!=null?K:[],l=d!==a,h=JSON.stringify(u)!==JSON.stringify(g);if(!l&&!h)return;let r=((O=o==null?void 0:o.author)!=null?O:i==null?void 0:i.author)||{id:"unknown",username:"Unknown"};Y(s).push({type:"edit",messageId:c,channelId:s,author:r,timestamp:Date.now(),contentBefore:d,contentAfter:a,embedsBefore:u,embedsAfter:g});let m=(W=r==null?void 0:r.username)!=null?W:"Unknown",S=B(u),b=B(g),w=`edited message by ${m}`;l&&(w+=`
Before:
${d||"[no content]"}
After:
${a||"[no content]"}`);let D=[];(h||S||b)&&(S&&D.push(`Embeds (before):
${S}`),b&&D.push(`Embeds (after):
${b}`)),nn(s,w,D.length?D.join(`

`):null)});_.push(n)}function hn(){if(!E)return;let n=en.bind(null),t=un.bind(null);E.subscribe("MESSAGE_DELETE",n),E.subscribe("MESSAGE_DELETE_BULK",t),_.push(()=>{try{E.unsubscribe("MESSAGE_DELETE",n)}catch(e){}try{E.unsubscribe("MESSAGE_DELETE_BULK",t)}catch(e){}})}function dn(){if(!H||!M||!T||!V||!Q)return;let n=H("openLazy",M,(t,e)=>{var i,o;let[s]=t!=null?t:[];!s||((i=s.name)!=null?i:s.displayName)!=="ChannelLongPressActionSheet"||(o=e==null?void 0:e.then)==null||o.call(e,d=>{let a=d==null?void 0:d.default;a&&(d.default=u=>{let g=a(u);try{let l=V(g,h=>Array.isArray(h)&&h.some(r=>(r==null?void 0:r.type)===T.ActionSheetRow));Array.isArray(l)&&l.push(Q.createElement(T.ActionSheetRow,{key:"nodelete-clear-log",label:"Clear log",onPress:()=>{var h,r;try{let m=(r=(h=u==null?void 0:u.channel)==null?void 0:h.id)!=null?r:u==null?void 0:u.channelId;if(m){f.logs[m]&&(f.logs[m]=[]);let S=Z(m);for(let b of S)try{E.dispatch({type:"MESSAGE_DELETE",channelId:m,id:b})}catch(w){}f.uiMessageIds[m]=[]}typeof X=="function"&&X("Cleared NoDelete log",1)}catch(m){}M.hideActionSheet()}}))}catch(l){}return g})})});_.push(n)}var gn={onLoad(){try{fn()}catch(n){}try{hn()}catch(n){}try{dn()}catch(n){}},onUnload(){for(;_.length;)try{let n=_.pop();n&&n()}catch(n){}}};typeof v!="undefined"&&(v.exports=gn)});ln();})();
